static String decksList[] = { "60",
"60",
"",
"Thief 100",
"0",
"Fire Demon T (10)",
"Behemoth T (10)",
"Polar Bearborn T (5)",
"Swamp Golem T (8)",
"Demonic Imp T (9)",
"Demonic Imp T (9)",
"Water Elemental T (10)",
"Water Elemental T (10)",
"Ice Dragon T (10)",
"Kitsune T (10)",
"",
"Ancient Oni 54 npc",
"54",
"blackstone (8)",
"ancient oni (8)",
"fire demon (8)",
"taiga cleric (10)",
"fire demon (10)",
"draconian shaman (10)",
"behemoth (8)",
"draconian imp (10)",
"magma frostblade (10)",
"Rune: Inferno (4)",
"Rune: Fire Forge (4)",
"Rune: Explosion (4)",
"Rune: Swampwater (4)",
"",
"Magma Frostblade 74 npc",
"74",
"magma frostblade (10)",
"magma frostblade (10)",
"statue of light (10)",
"fire kirin (5)",
"stone taurus (10)",
"taiga general (5)",
"taiga general (5)",
"blazing lion (10)",
"undead warrior (10)",
"Rune: Spring Breeze (3)",
"Rune: Death Zone (1)",
"Rune: Blizzard (2)",
"Rune: Fire Forge (4)",
"",
"Moss Dragon 72 npc",
"72",
"Polar Bearborn (10)",
"polar bearborn (10)",
"taurus guard (10)",
"undead warrior (10)",
"bronze dragon (10)",
"stone taurus (10)",
"arctic sea dragon (10)",
"moss dragon (5)",
"blackstone (10)",
"Rune: Blood Stone (3)",
"Rune: Tsunami (3)",
"Rune: Spring Breeze (3)",
"Rune: Death Zone (4)",
"",
"Ice Dragon 52 npc1",
"52",
"ice dragon (10)",
"ice dragon (8)",
"water elemental (10)",
"water elemental (10)",
"forest giant (10)",
"forest giant (8)",
"kitsune (10)",
"kitsune (8)",
"moss dragon (8)",
"behemoth (8)",
"Rune: Lightning (4)",
"Rune: Thunder Shield (4)",
"Rune: Spring Breeze (4)",
"Rune: Blood Stone (4)",
"",
"Ice Dragon 52 npc2",
"52",
"arctic sea dragon (8)",
"arctic sea dragon (8)",
"taiga general (8)",
"taiga general (8)",
"terra cotta warrior(10)",
"terra cotta warrior (8)",
"Moss dragon (8)",
"kitsune (8)",
"ice dragon (8)",
"Rune: Lightning (3)",
"Rune: Thunder Shield (3)",
"Rune: Spring Breeze (3)",
"Rune: Blood Stone (3)",
"",
"Fire Demon 56 npc",
"56",
"Behemoth (10)",
"Behemoth (8)",
"Fire Demon (10)",
"Fire Demon (10)",
"Ancient Oni (10)",
"Ancient Oni (8)",
"undead warrior (8)",
"cerato (10)",
"ankylo (10)",
"blackstone (10)",
"Rune: Death Zone (4)",
"Rune: Red Valley (4)",
"Rune: Stone Forest (4)",
"Rune: Quicksand (4)",
"",
"TCW 71 npc",
"71",
"cerato (10)",
"blackstone (10)",
"terra cotta warrior (10)",
"coiled dragon (10)",
"dire snapping turtle (10)",
"undead warrior (10)",
"swamp golem (10)",
"behemoth (10)",
"taiga general (10)",
"draconian shaman (10)",
"Rune: explosion (1)",
"Rune: clear spring (3)",
"Rune: transparency (3)",
"Rune: swampwater (2)",
"",
"DST 55 npc",
"55",
"fire demon (10)",
"fire demon (8)",
"demonic imp (10)",
"demonic imp (10)",
"draconian shaman (10)",
"draconian shaman (8)",
"dire snapping turtle (10)",
"dire snapping turtle (10)",
"dire snapping turtle (8)",
"taiga cleric (10)",
"Rune: inferno (4)",
"Rune: fire forge (4)",
"Rune: explosion (4)",
"Rune: blood stone (4)",
"",
"Ice Dragon 53 npc",
"53",
"taiga general (10)",
"taiga general (8)",
"arctic sea dragon (10)",
"arctic sea dragon (10)",
"arctic sea dragon (8)",
"terra cotta warrior (10)",
"terra cotta warrior (10)",
"ice dragon (10)",
"moss dragon (8)",
"kitsune (8)",
"Rune: permafrost (4)",
"Rune: avalanche (4)",
"Rune: arctic freeze (4)",
"Rune: clear spring (4)",
"",
"Ice Dragon 51 npc",
"51",
"arctic sea dragon (7)",
"arctic sea dragon (6)",
"taiga general (6)",
"taiga general (6)",
"terra cotta warrior (8)",
"terra cotta warrior (8)",
"moss dragon (6)",
"kitsune (7)",
"ice dragon (6)",
"Rune: permafrost (2)",
"Rune: avalanche (2)",
"Rune: arctic freeze (2)",
"Rune: clear spring (2)",
};

