static String KWdecksList[] = { "60",
"60",
"",
"Ancient Oni 54 npc",
"54",
"blackstone;8",
"ancient oni;8",
"fire demon;8",
"taiga cleric;10",
"fire demon;10",
"draconian shaman;10",
"behemoth;8",
"draconian imp;10",
"magma frostblade;10",
"Rune: Inferno;4",
"Rune: Fire Forge;4",
"Rune: Explosion;4",
"Rune: Swampwater;4",
"",
"DST 55 npc",
"55",
"fire demon;10",
"fire demon;8",
"demonic imp;10",
"demonic imp;10",
"draconian shaman;10",
"draconian shaman;8",
"dire snapping turtle;10",
"dire snapping turtle;10",
"dire snapping turtle;8",
"taiga cleric;10",
"Rune: inferno;4",
"Rune: fire forge;4",
"Rune: explosion;4",
"Rune: blood stone;4",
"",
"Fire Demon 56 npc",
"56",
"Behemoth;10",
"Behemoth;8",
"Fire Demon;10",
"Fire Demon;10",
"Ancient Oni;10",
"Ancient Oni;8",
"undead warrior;8",
"cerato;10",
"ankylo;10",
"blackstone;10",
"Rune: Death Zone;4",
"Rune: Red Valley;4",
"Rune: Stone Forest;4",
"Rune: Quicksand;4",
"",
"Ice Dragon 52 npc1",
"52",
"ice dragon;10",
"ice dragon;8",
"water elemental;10",
"water elemental;10",
"forest giant;10",
"forest giant;8",
"kitsune;10",
"kitsune;8",
"moss dragon;8",
"behemoth;8",
"Rune: Lightning;4",
"Rune: Thunder Shield;4",
"Rune: Spring Breeze;4",
"Rune: Blood Stone;4",
"",
"Ice Dragon 52 npc2",
"52",
"arctic sea dragon;8",
"arctic sea dragon;8",
"taiga general;8",
"taiga general;8",
"terra cotta warrior;10",
"terra cotta warrior;8",
"Moss dragon;8",
"kitsune;8",
"ice dragon;8",
"Rune: Lightning;3",
"Rune: Thunder Shield;3",
"Rune: Spring Breeze;3",
"Rune: Blood Stone;3",
"",
"Ice Dragon 53 npc",
"53",
"taiga general;10",
"taiga general;8",
"arctic sea dragon;10",
"arctic sea dragon;10",
"arctic sea dragon;8",
"terra cotta warrior;10",
"terra cotta warrior;10",
"ice dragon;10",
"moss dragon;8",
"kitsune;8",
"Rune: permafrost;4",
"Rune: avalanche;4",
"Rune: arctic freeze;4",
"Rune: clear spring;4",
"",
"Magma Frostblade 74 npc",
"74",
"magma frostblade;10",
"magma frostblade;10",
"statue of light;10",
"fire kirin;5",
"stone taurus;10",
"taiga general;5",
"taiga general;5",
"blazing lion;10",
"undead warrior;10",
"Rune: Spring Breeze;3",
"Rune: Death Zone;1",
"Rune: Blizzard;2",
"Rune: Fire Forge;4",
"",
"Moss Dragon 72 npc",
"72",
"Polar Bearborn;10",
"polar bearborn;10",
"taurus guard;10",
"undead warrior;10",
"bronze dragon;10",
"stone taurus;10",
"arctic sea dragon;10",
"moss dragon;5",
"blackstone;10",
"Rune: Blood Stone;3",
"Rune: Tsunami;3",
"Rune: Spring Breeze;3",
"Rune: Death Zone;4",
"",
"TCW 71 npc",
"71",
"cerato;10",
"blackstone;10",
"terra cotta warrior;10",
"coiled dragon;10",
"dire snapping turtle;10",
"undead warrior;10",
"swamp golem;10",
"behemoth;10",
"taiga general;10",
"draconian shaman;10",
"Rune: explosion;1",
"Rune: clear spring;3",
"Rune: transparency;3",
"Rune: swampwater;2",
"",
};

static String ThiefdecksList[] = { "60",
"60",
"",
"Thief 100",
"0",
"Behemoth T;10",
"Ice Dragon T;10",
"Fire Demon T;10",
"Water Elemental T;10",
"Water Elemental T;10",
"Kitsune T;10",
"Demonic Imp T;9",
"Demonic Imp T;9",
"Swamp Golem T;8",
"Polar Bearborn T;5",
"",
"Leg Thief lvl 100",
"0",
"Behemoth LT;10",
"Ice Dragon LT;10",
"Fire Demon LT;10",
"Water Elemental LT;10",
"Water Elemental LT;10",
"Kitsune LT;10",
"Demonic Imp LT;9",
"Demonic Imp LT;9",
"Swamp Golem LT;8",
"Polar Bearborn LT;5",
"",
};


static String DemondecksList[] = { "60",
"60",
"",
"Demon Azathoth",
"0",
"Azathoth;10",
"",
"Demon Bahamut",
"0",
"Bahamut;10",
"",
"Demon Dark Titan",
"0",
"Dark Titan;10",
"",
"Demon Deucalion",
"0",
"Deucalion;10",
"",
"Demon Mars",
"0",
"Mars;10",
"",
"Demon Pandarus",
"0",
"Pandarus;10",
"",
"Demon Pazuzu",
"0",
"Pazuzu;10",
"",
"Demon Plague Ogryn",
"0",
"Plague Ogryn;10",
"",
"Demon Sea King",
"0",
"Sea King;10",
"",
};

static String EWdecksList[] = { "60",
"60",
"",
"EW Aranyani",
"0",
"Aranyani [Legendary];15",
"Serpent Shamanka;15;mc10",
"Serpent Shamanka;15;mc10",
"Orc Teacher;15;res1",
"Orc Teacher;15;res1",
"Black Thorn;15;res1",
"Everglade Mermaid;15;res1",
"Lightning Pumpkin;15;es8",
"Christmas Treant;15;res1",
"Prince of the Forest;15;res1",
"",
"EW Arctic Cephalid",
"0",
"Arctic Cephalid [Legendary];15",
"Ice Knight;15;res1",
"Sea Piercer;15;bzd8",
"Steel Dragon;15;res1",
"Tundra Rider;15;res1",
"Sea Piercer;15;bzd8",
"Crystal Emperor;15;res1",
"Steel Dragon;15;res1",
"Ice Knight;15;res1",
"Tundra Rider;15;res1",
"",
"EW Armored Sumatran",
"0",
"Armored Sumatran [Legendary];15",
"Exiled Angel;15;res1",
"Empyrean Priestess;15;res1",
"Orc Teacher;15;res1",
"Everglade Mermaid;15;res1",
"Nuriel;15;res1",
"Steel Executioner;15;res1",
"Behemoth;15;ret8",
"Behemoth;15;ret8",
"Giant Mud Larva;15;res1",
"",
"EW Behemoth",
"0",
"Behemoth [Legendary];15",
"Zombie Dragon;15;trp2",
"Zombie Dragon;15;trp2",
"Abhorrent Gargoyle;15;tc10",
"Abhorrent Gargoyle;15;tc10",
"Orc Teacher;15;res1",
"Orc Teacher;15;res1",
"Serpent Shamanka;15;mc10",
"Serpent Shamanka;15;mc10",
"Everglade Mermaid;15;res1",
"",
"EW Everglade Mermaid",
"0",
"Everglade Mermaid [Legendary];15",
"Behemoth;15;tc10",
"Behemoth;15;tc10",
"Zombie Dragon;15;tc10",
"Zombie Dragon;15;tc10",
"Orc Teacher;15;res1",
"Serpent Shamanka;15;tc10",
"Toxic Pumpkin;15;tc10",
"Marsh Devourer;15;res1",
"Venomripper;15;eva1",
"",
"EW Fire Demon",
"0",
"Fire Demon [Legendary];15",
"Dire Snapping Turtle;15;res1",
"Dire Snapping Turtle;15;res1",
"Azula;15;res1",
"Azula;15;res1",
"Fire Berserker;15;res1",
"Fire Berserker;15;res1",
"Winged Exile;15;res1",
"Winged Exile;15;res1",
"Queen of the Dead;15;trp2",
"",
"EW Ice Dragon",
"0",
"Ice Dragon [Legendary];15",
"Arctic Cephalid;15;res1",
"Crystal Emperor;15;res1",
"Marsh Devourer;15;res1",
"Evil Empress;15;res1",
"Taiga General;15;res1",
"Goblin Engineer;15;res1",
"Evil Empress;15;res1",
"Marsh Devourer;15;res1",
"Ice Knight;15;res1",
"",
"EW Marsh Devourer",
"0",
"Marsh Devourer [Legendary];15",
"Marsh Devourer;15;res1",
"Moor Ripper;15;res1",
"Abhorrent Gargoyle;15;tc8",
"Giant Mud Larva;15;res1",
"Arctic Cephalid;15;res1",
"Crystal Emperor;15;res1",
"Ice Knight;15;res1",
"Marsh Devourer;15;res1",
"Marsh Devourer;15;res1",
"",
"EW Moor Ripper",
"0",
"Moor Ripper [Legendary];15",
"Orc Teacher;15;res1",
"Everglade Mermaid;15;res1",
"Dire Snapping Turtle;15;res1",
"Winged Exile;15;res1",
"Giant Mud Larva;15;res1",
"Steel Executioner;15;res1",
"Serpent Shamanka;15;tc10",
"Evil Empress;15;res1",
"Mountain King;15;res1",
"",
"EW Night Elf Ranger",
"0",
"Night Elf Ranger [Legendary];15",
"Exiled Angel;15;res1",
"Exiled Angel;15;res1",
"Empyrean Priestess;15;res1",
"Empyrean Priestess;15;res1",
"Lightning Pumpkin;15;ret8",
"Lightning Pumpkin;15;ret8",
"Rose Knight;15;res1",
"Rose Knight;15;res1",
"Fire Kirin;15;res1",
"",
"EW Nuriel",
"0",
"Nuriel [Legendary];15",
"Molten Pumpkin;15;d:fs10",
"Armored Turkey;15;res1",
"Dire Snapping Turtle;15;imm1",
"Fire Demon;15;d:fs10",
"Behemoth;15;tc10",
"Zombie Dragon;15;tc10",
"Marsh Devourer;15;res1",
"Sea Piercer;15;bzd10",
"Lightning Pumpkin;15;es10",
"",
"EW Omniscient Dragon",
"0",
"Omniscient Dragon [Legendary];15",
"Exiled Angel;15;res1",
"Ice Sprite;15;res1",
"Empyrean Priestess;15;res1",
"Orc Teacher;15;res1",
"Orc Teacher;15;res1",
"Serpent Shamanka;15;mc10",
"Serpent Shamanka;15;mc10",
"Everglade Mermaid;15;res1",
"Prince of the Forest;15;res1",
"",
"EW Rose Knight",
"0",
"Rose Knight [Legendary];15",
"Moss Dragon;15;es10",
"Winged Tiger;15;res1",
"Exiled Angel;15;res1",
"Jack Frost;15;res1",
"Shadow Assassin;15;res1",
"Rose Knight;15;res1",
"Steel Dragon;15;res1",
"Prince of the Forest;15;res1",
"Winter Samurai;15;res1",
"",
"EW Sea Piercer",
"0",
"Sea Piercer [Legendary];15",
"Arctic Cephalid;15;res1",
"Crystal Emperor;15;res1",
"Light Paladin;15;bzd10",
"Taiga Archon;15;eva1",
"Rose Knight;15;res1",
"Arbiter of War;15;res1",
"Dire Snapping Turtle;15;res1",
"Steel Executioner;15;res1",
"Orc Teacher;15;res1",
"",
"EW Taiga General",
"0",
"Taiga General [Legendary];15",
"Ice Dragon;15;bzd8",
"Ice Dragon;15;bzd8",
"Dharmanian;15;res1",
"Dharmanian;15;res1",
"Shadow Assassin;15;res1",
"Shadow Assassin;15;res1",
"Santa;15;trp2",
"Santa;15;trp2",
"Arctic Lich;15;nf7",
"",
"EW Winged Exile",
"0",
"Winged Exile [Legendary];15",
"Nuriel;15;res1",
"Giant Mud Larva;15;res1",
"Giant Mud Larva;15;res1",
"Behemoth;15;ret8",
"Behemoth;15;ret8",
"Fire Berserker;15;res1",
"Steel Executioner;15;res1",
"Queen of the Dead;15;fs8",
"Marsh Devourer;15;res1",
"",
"EW Winter Samurai",
"0",
"Winter Samurai [Legendary];15",
"Tundra Rider;15;res1",
"Nuriel;15;res1",
"Ancient One;15;res1",
"Arctic Lich;15;bzd10",
"Ice Knight;15;res1",
"Armored Sumatran;15;eva1",
"Goblin Engineer;15;res1",
"Santa;15;bzd10",
"Evil Empress;15;res1",
"",
};

static String HydradecksList[] = { "60",
"60",
"",
"Hydra I",
"0",
"Hydra I;10",
"Troglodyte;10",
"Kitsune;10",
"Water Elemental;10",
"Mischievous Pixie;10",
"Frost Troll Mage;10",
"Snow Lotus Sprite;10",
"Fire Golem;10",
"Crystal Golem;10",
"Fallen Angel;10",
"Rune: thunderbolt;2",
"Rune: coldwave;2",
"Rune: permafrost;2",
"",
"Hydra II Curse",
"0",
"Hydra II [Curse];10",
"Lava Destroyer;10",
"Lava Destroyer;10",
"Draconian Elder;10",
"Draconian Elder;10",
"Mermaid Princess;10",
"Fire-Cursed Treant;10",
"Fire-Cursed Treant;10",
"Omniscient Dragon;10",
"Fire Berserker;10",
"Rune: Burning Soul;4",
"Rune: Inferno;4",
"Rune: Lore;4",
"Rune: Charred;4",
"",
"Hydra II Freeze",
"0",
"Hydra II [Freeze];10",
"Mischievous Pixie;10",
"Water Elemental;10",
"Kitsune;10",
"Magma Frostblade;10",
"Fire Kirin;10",
"Blackstone;10",
"Alicorn;10",
"Night Kirin;10",
"Night Kirin;10",
"Rune: Spring Breeze;4",
"Rune: Raised Flag;4",
"Rune: Lightning;4",
"Rune: Thunder Shield;4",
"",
"Hydra II Reflect",
"0",
"Hydra II [Reflect];10",
"Arctic Drake;10",
"Cerato;10",
"Snow Crusader;10",
"Thorn Queen;10",
"Headless Horseman;10",
"Fire Gorilla;10",
"Alanine;10",
"Polar Bearborn;10",
"Undead Felldrake;10",
"Rune: Icicle;4",
"Rune: Fire FLow;4",
"Rune: Thunderbolt;4",
"Rune: Stone Forest;4",
"",
"Hydra II Trap",
"0",
"Hydra II [Trap];10",
"Red Lotus Sprite;10",
"Forest Giant;10",
"Terra Cotta Warrior;10",
"Taiga Archon;10",
"Water Elemental;10",
"Omniscient Dragon;10",
"Vine Horror;10",
"Thorn Queen;10",
"Rune: Quicksand;4",
"Rune: Arsenopyrite;4",
"Rune: Blizzard;4",
"Rune: Explosion;4",
"",
"Hydra II Weaken",
"0",
"Hydra II [Weaken];10",
"Demonic Imp;10",
"Snow Ogre;10",
"Foxtail Nymph;10",
"Foxtail Nymph;10",
"Dharmanian;10",
"Bronze Dragon;10",
"Spirit Ghost;10",
"Latite Golem;10",
"Draconian Warrior;10",
"Rune: Lore;4",
"Rune: THunder Shield;4",
"Rune: Stone Forest;4",
"Rune: Spring Breeze;4",
"",
"Hydra III Curse",
"0",
"Hydra III [Curse];10",
"Terra Cotta Warrior;10",
"Fire Demon;10",
"Fire Berserker;10",
"Taiga General;10",
"Taiga General;10",
"Dharmanian;10",
"Draconian Elder;10",
"Lava Destroyer;10",
"Lava Destroyer;10",
"Rune: Clear Spring;4",
"Rune: Arctic Freeze;4",
"Rune: Burning Soul;4",
"Rune: Charred;4",
"",
"Hydra III Freeze",
"0",
"Hydra III [Freeze];10",
"Behemoth;10",
"Terra Cotta Warrior;10",
"Water Elemental;10",
"Grand Lich;10",
"Manscorpion;10",
"Kitsune;10",
"Aranyani;10",
"Mermaid Princess;10",
"Fire Kirin;10",
"Rune: Avalanche;4",
"Rune: Spring Breeze;4",
"Rune: Nimble Soul;4",
"Rune: Thunder Shield;4",
"",
"Hydra III Poison",
"0",
"Hydra III [Poison];10",
"Abhorrent Gargoyle;10",
"Zombie Dragon;10",
"Zombie Dragon;10",
"Snow Ogre;10",
"Snow Ogre;10",
"Dire Snapping Turtle;10",
"Latite Golem;10",
"Frostree-Folk;10",
"Grand Lich;10",
"Rune: stone forest;4",
"Rune: death zone;4",
"Rune: red valley;4",
"Rune: stonewall;4",
"",
"Hydra III Reflect",
"0",
"Hydra III [Reflect];10",
"Lord of the Mire;10",
"Vampire Bat Demon;10",
"Demonic Imp;10",
"Dragon Knight;10",
"Taurus Guard;10",
"Arctic Cephalid;10",
"Fire Demon;10",
"Moss Dragon;10",
"Cerato;10",
"Rune: stone forest;4",
"Rune: death zone;4",
"Rune: flying stone;4",
"Rune: stonewall;4",
"",
"Hydra III Trap",
"0",
"Hydra III [Trap];10",
"Demonic Imp;10",
"Armored Sumatran;10",
"Terra Cotta Warrior;10",
"Arctic Drake;10",
"Thunder Dragon;10",
"Lord of the Mire;10",
"Azula;10",
"Dire Snapping Turtle;10",
"Water Elemental;10",
"Rune: Avalanche;4",
"Rune: Quicksand;4",
"Rune: Transparency;4",
"Rune: Explosion;4",
"",
"Hydra IV Craze",
"0",
"Hydra IV [Craze];10",
"Behemoth;10",
"Taiga General;10",
"Taiga General;10",
"Cacti Guardian;10",
"Dharmanian;10",
"Winged Tiger;10",
"Void Blademaster;10",
"Rune: Red Valley;4",
"Rune: Arctic Freeze;4",
"Rune: Stonewall;4",
"Rune: Transparency;4",
"",
"Hydra IV Fire",
"0",
"Hydra IV [Fire];10",
"Abhorrent Gargoyle;10",
"Behemoth;10",
"Behemoth;10",
"Water Elemental;10",
"Manscorpion;10",
"Fire Kirin;10",
"Fire Kirin;10",
"Aranyani;10",
"Bronze Dragon;10",
"Rune: Stonewall;4",
"Rune: Lightning;4",
"Rune: Spring Breeze;4",
"Rune: Thunder Shield;4",
"",
"Hydra IV Leech",
"0",
"Hydra IV [Leech];10",
"Magma Frostblade;10",
"Moor Ripper;10",
"Moss Dragon;10",
"Skeleton King;10",
"Ice Dragon;10",
"Fire Demon;10",
"Behemoth;10",
"Blackstone;10",
"Stone Taurus;10",
"Rune: Avalanche;4",
"Rune: Transparency;4",
"Rune: Quicksand;4",
"Rune: Explosion;4",
"",
"Hydra IV Snipe",
"0",
"Hydra IV [Snipe];10",
"Moss Dragon;10",
"Moss Dragon;10",
"Terra Cotta Warrior;10",
"Arctic Cephalid;10",
"Arctic Cephalid;10",
"Winged Tiger;10",
"Frostree-Folk;10",
"Taiga General;10",
"Cacti Guardian;10",
"Rune: arctic freeze;4",
"Rune: clear spring;4",
"Rune: permafrost;4",
"Rune: frost bite;4",
"",
"Hydra IV Teleport",
"0",
"Hydra IV [Teleport];10",
"Demonic Imp;10",
"Fire Demon;10",
"Armored Sumatran;10",
"Taiga Archon;10",
"Dragon Knight;10",
"Dire Snapping Turtle;10",
"Red Banded Dragon;10",
"Night Elf Ranger;10",
"Thunder Dragon;10",
"Rune: Burning soul;4",
"Rune: Charred;4",
"Rune: Lore;4",
"Rune: Thunder Shield;4",
"",
"Hydra V Exile",
"0",
"Hydra V [Exile];10",
"Taiga General;10",
"Taiga General;10",
"Taiga General;10",
"Taiga General;10",
"Lava Destroyer;10",
"Azula;10",
"Azula;10",
"Azula;10",
"Azula;10",
"Rune: Burning Soul;4",
"Rune: Clear Spring;4",
"Rune: Arctic Freeze;4",
"Rune: Lore;4",
"",
"Hydra V Guard",
"0",
"Hydra V [Guard];10",
"Moss Dragon;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Fire Demon;10",
"Fire Demon;10",
"Dire Snapping Turtle;10",
"Arbiter of War;10",
"Prince of the Forest;10",
"Rune: Thunder Shield;4",
"Rune: Lightning;4",
"Rune: Nimble Soul;4",
"Rune: Lore;4",
"",
"Hydra V Leech",
"0",
"Hydra V [Leech];10",
"Ice Dragon;10",
"Ice Dragon;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Crystal Emperor;10",
"Taiga General;10",
"Taiga General;10",
"Fire Kirin;10",
"Rune: Thunder Shield;4",
"Rune: Arctic Freeze;4",
"Rune: Clear Spring;4",
"Rune: Nimble Soul;4",
"",
"Hydra V Retaliate",
"0",
"Hydra V [Retaliate];10",
"Behemoth;10",
"Behemoth;10",
"Behemoth;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Moss Dragon;10",
"Giant Mud Larva;10",
"Grand Lich;10",
"Rune: Thunder Shield;4",
"Rune: Death zone;4",
"Rune: Red Valley;4",
"Rune: Stonewall;4",
"",
"Hydra V Witch",
"0",
"Hydra V [Witch];10",
"Behemoth;10",
"Behemoth;10",
"Behemoth;10",
"Ice Dragon;10",
"Ice Dragon;10",
"Giant Mud Larva;10",
"Taiga General;10",
"Taiga General;10",
"Grand Lich;10",
"Rune: red valley;4",
"Rune: arctic freeze;4",
"Rune: clear spring;4",
"Rune: flying stone;4",
"",
};
