static String KWdecksList[] = { "60",
"60",
"",
"Ancient Oni 54 npc",
"54",
"blackstone;8",
"ancient oni;8",
"fire demon;8",
"taiga cleric;10",
"fire demon;10",
"draconian shaman;10",
"behemoth;8",
"draconian imp;10",
"magma frostblade;10",
"Rune: Inferno;4",
"Rune: Fire Forge;4",
"Rune: Explosion;4",
"Rune: Swampwater;4",
"",
"DST 55 npc",
"55",
"fire demon;10",
"fire demon;8",
"demonic imp;10",
"demonic imp;10",
"draconian shaman;10",
"draconian shaman;8",
"dire snapping turtle;10",
"dire snapping turtle;10",
"dire snapping turtle;8",
"taiga cleric;10",
"Rune: inferno;4",
"Rune: fire forge;4",
"Rune: explosion;4",
"Rune: blood stone;4",
"",
"Fire Demon 56 npc",
"56",
"Behemoth;10",
"Behemoth;8",
"Fire Demon;10",
"Fire Demon;10",
"Ancient Oni;10",
"Ancient Oni;8",
"undead warrior;8",
"cerato;10",
"ankylo;10",
"blackstone;10",
"Rune: Death Zone;4",
"Rune: Red Valley;4",
"Rune: Stone Forest;4",
"Rune: Quicksand;4",
"",
"Ice Dragon 52 npc1",
"52",
"ice dragon;10",
"ice dragon;8",
"water elemental;10",
"water elemental;10",
"forest giant;10",
"forest giant;8",
"kitsune;10",
"kitsune;8",
"moss dragon;8",
"behemoth;8",
"Rune: Lightning;4",
"Rune: Thunder Shield;4",
"Rune: Spring Breeze;4",
"Rune: Blood Stone;4",
"",
"Ice Dragon 52 npc2",
"52",
"arctic sea dragon;8",
"arctic sea dragon;8",
"taiga general;8",
"taiga general;8",
"terra cotta warrior;10",
"terra cotta warrior;8",
"Moss dragon;8",
"kitsune;8",
"ice dragon;8",
"Rune: Lightning;3",
"Rune: Thunder Shield;3",
"Rune: Spring Breeze;3",
"Rune: Blood Stone;3",
"",
"Ice Dragon 53 npc",
"53",
"taiga general;10",
"taiga general;8",
"arctic sea dragon;10",
"arctic sea dragon;10",
"arctic sea dragon;8",
"terra cotta warrior;10",
"terra cotta warrior;10",
"ice dragon;10",
"moss dragon;8",
"kitsune;8",
"Rune: permafrost;4",
"Rune: avalanche;4",
"Rune: arctic freeze;4",
"Rune: clear spring;4",
"",
"Magma Frostblade 74 npc",
"74",
"magma frostblade;10",
"magma frostblade;10",
"statue of light;10",
"fire kirin;5",
"stone taurus;10",
"taiga general;5",
"taiga general;5",
"blazing lion;10",
"undead warrior;10",
"Rune: Spring Breeze;3",
"Rune: Death Zone;1",
"Rune: Blizzard;2",
"Rune: Fire Forge;4",
"",
"Moss Dragon 72 npc",
"72",
"Polar Bearborn;10",
"polar bearborn;10",
"taurus guard;10",
"undead warrior;10",
"bronze dragon;10",
"stone taurus;10",
"arctic sea dragon;10",
"moss dragon;5",
"blackstone;10",
"Rune: Blood Stone;3",
"Rune: Tsunami;3",
"Rune: Spring Breeze;3",
"Rune: Death Zone;4",
"",
"TCW 71 npc",
"71",
"cerato;10",
"blackstone;10",
"terra cotta warrior;10",
"coiled dragon;10",
"dire snapping turtle;10",
"undead warrior;10",
"swamp golem;10",
"behemoth;10",
"taiga general;10",
"draconian shaman;10",
"Rune: explosion;1",
"Rune: clear spring;3",
"Rune: transparency;3",
"Rune: swampwater;2",
"",
};

static String ThiefdecksList[] = { "60",
"60",
"",
"Thief 100",
"0",
"Behemoth T;10",
"Ice Dragon T;10",
"Fire Demon T;10",
"Water Elemental T;10",
"Water Elemental T;10",
"Kitsune T;10",
"Demonic Imp T;9",
"Demonic Imp T;9",
"Swamp Golem T;8",
"Polar Bearborn T;5",
"",
"Leg Thief lvl 100",
"0",
"Behemoth LT;10",
"Ice Dragon LT;10",
"Fire Demon LT;10",
"Water Elemental LT;10",
"Water Elemental LT;10",
"Kitsune LT;10",
"Demonic Imp LT;9",
"Demonic Imp LT;9",
"Swamp Golem LT;8",
"Polar Bearborn LT;5",
"",
};


static String DemondecksList[] = { "60",
"60",
"",
"Demon Azathoth",
"0",
"Azathoth;10",
"",
"Demon Bahamut",
"0",
"Bahamut;10",
"",
"Demon Dark Titan",
"0",
"Dark Titan;10",
"",
"Demon Deucalion",
"0",
"Deucalion;10",
"",
"Demon Mars",
"0",
"Mars;10",
"",
"Demon Pandarus",
"0",
"Pandarus;10",
"",
"Demon Pazuzu",
"0",
"Pazuzu;10",
"",
"Demon Plague Ogryn",
"0",
"Plague Ogryn;10",
"",
"Demon Sea King",
"0",
"Sea King;10",
"",
};


static String HydradecksList[] = { "60",
"60",
"",
"Hydra I",
"0",
"Hydra I;10",
"Troglodyte;10",
"Kitsune;10",
"Water Elemental;10",
"Mischievous Pixie;10",
"Frost Troll Mage;10",
"Snow Lotus Sprite;10",
"Fire Golem;10",
"Crystal Golem;10",
"Fallen Angel;10",
"Rune: thunderbolt;2",
"Rune: coldwave;2",
"Rune: permafrost;2",
"",
"Hydra II Curse",
"0",
"Hydra II [Curse];10",
"H2-Lava Destroyer;10",
"H2-Lava Destroyer;10",
"H2-Draconian Elder;10",
"H2-Draconian Elder;10",
"H2-Mermaid Princess;10",
"H2-Fire-Cursed Treant;10",
"H2-Fire-Cursed Treant;10",
"H2-Omniscient Dragon;10",
"H2-Fire Berserker;10",
"Rune: Burning Soul;4",
"Rune: Inferno;4",
"Rune: Lore;4",
"Rune: Charred;4",
"",
"Hydra II Freeze",
"0",
"Hydra II [Freeze];10",
"H2-Mischievous Pixie;10",
"H2-Water Elemental;10",
"H2-Kitsune;10",
"H2-Magma Frostblade;10",
"H2-Fire Kirin;10",
"H2-Blackstone;10",
"H2-Alicorn;10",
"H2-Night Kirin;10",
"H2-Night Kirin;10",
"Rune: Spring Breeze;4",
"Rune: Raised Flag;4",
"Rune: Lightning;4",
"Rune: Thunder Shield;4",
"",
"Hydra II Reflect",
"0",
"Hydra II [Reflect];10",
"H2-Arctic Drake;10",
"H2-Cerato;10",
"H2-Snow Crusader;10",
"H2-Thorn Queen;10",
"H2-Headless Horseman;10",
"H2-Fire Gorilla;10",
"H2-Alanine;10",
"H2-Polar Bearborn;10",
"H2-Undead Felldrake;10",
"Rune: Icicle;4",
"Rune: Fire FLow;4",
"Rune: Thunderbolt;4",
"Rune: Stone Forest;4",
"",
"Hydra II Trap",
"0",
"Hydra II [Trap];10",
"H2-Red Lotus Sprite;10",
"H2-Forest Giant;10",
"H2-Terra Cotta Warrior;10",
"H2-Taiga Archon;10",
"H2-Water Elemental;10",
"H2-Omniscient Dragon;10",
"H2-Vine Horror;10",
"H2-Thorn Queen;10",
"Rune: Quicksand;4",
"Rune: Arsenopyrite;4",
"Rune: Blizzard;4",
"Rune: Explosion;4",
"",
"Hydra II Weaken",
"0",
"Hydra II [Weaken];10",
"H2-Demonic Imp;10",
"H2-Snow Ogre;10",
"H2-Foxtail Nymph;10",
"H2-Foxtail Nymph;10",
"H2-Dharmanian;10",
"H2-Bronze Dragon;10",
"H2-Spirit Ghost;10",
"H2-Latite Golem;10",
"H2-Draconian Warrior;10",
"Rune: Lore;4",
"Rune: THunder Shield;4",
"Rune: Stone Forest;4",
"Rune: Spring Breeze;4",
"",
"Hydra III Curse",
"0",
"Hydra III [Curse];10",
"H3-Terra Cotta Warrior;10",
"H3-Fire Demon;10",
"H3-Fire Berserker;10",
"H3-Taiga General;10",
"H3-Taiga General;10",
"H3-Dharmanian;10",
"H3-Draconian Elder;10",
"H3-Lava Destroyer;10",
"H3-Lava Destroyer;10",
"Rune: Clear Spring;4",
"Rune: Arctic Freeze;4",
"Rune: Burning Soul;4",
"Rune: Charred;4",
"",
"Hydra III Freeze",
"0",
"Hydra III [Freeze];10",
"H3-Behemoth;10",
"H3-Terra Cotta Warrior;10",
"H3-Water Elemental;10",
"H3-Grand Lich;10",
"H3-Manscorpion;10",
"H3-Kitsune;10",
"H3-Aranyani;10",
"H3-Mermaid Princess;10",
"H3-Fire Kirin;10",
"Rune: Avalanche;4",
"Rune: Spring Breeze;4",
"Rune: Nimble Soul;4",
"Rune: Thunder Shield;4",
"",
"Hydra III Poison",
"0",
"Hydra III [Poison];10",
"H3-Abhorrent Gargoyle;10",
"H3-Zombie Dragon;10",
"H3-Zombie Dragon;10",
"H3-Snow Ogre;10",
"H3-Snow Ogre;10",
"H3-Dire Snapping Turtle;10",
"H3-Latite Golem;10",
"H3-Frostree-Folk;10",
"H3-Grand Lich;10",
"Rune: stone forest;4",
"Rune: death zone;4",
"Rune: red valley;4",
"Rune: stonewall;4",
"",
"Hydra III Reflect",
"0",
"Hydra III [Reflect];10",
"H3-Lord of the Mire;10",
"H3-Vampire Bat Demon;10",
"H3-Demonic Imp;10",
"H3-Dragon Knight;10",
"H3-Taurus Guard;10",
"H3-Arctic Cephalid;10",
"H3-Fire Demon;10",
"H3-Moss Dragon;10",
"H3-Cerato;10",
"Rune: stone forest;4",
"Rune: death zone;4",
"Rune: flying stone;4",
"Rune: stonewall;4",
"",
"Hydra III Trap",
"0",
"Hydra III [Trap];10",
"H3-Demonic Imp;10",
"H3-Armored Sumatran;10",
"H3-Terra Cotta Warrior;10",
"H3-Arctic Drake;10",
"H3-Thunder Dragon;10",
"H3-Lord of the Mire;10",
"H3-Azula;10",
"H3-Dire Snapping Turtle;10",
"H3-Water Elemental;10",
"Rune: Avalanche;4",
"Rune: Quicksand;4",
"Rune: Transparency;4",
"Rune: Explosion;4",
"",
"Hydra IV Craze",
"0",
"Hydra IV [Craze];10",
"H4-Behemoth;10",
"H4-Taiga General;10",
"H4-Taiga General;10",
"H4-Cacti Guardian;10",
"H4-Dharmanian;10",
"H4-Winged Tiger;10",
"H4-Void Blademaster;10",
"Rune: Red Valley;4",
"Rune: Arctic Freeze;4",
"Rune: Stonewall;4",
"Rune: Transparency;4",
"",
"Hydra IV Fire",
"0",
"Hydra IV [Fire];10",
"H4-Abhorrent Gargoyle;10",
"H4-Behemoth;10",
"H4-Behemoth;10",
"H4-Water Elemental;10",
"H4-Manscorpion;10",
"H4-Fire Kirin;10",
"H4-Fire Kirin;10",
"H4-Aranyani;10",
"H4-Bronze Dragon;10",
"Rune: Stonewall;4",
"Rune: Lightning;4",
"Rune: Spring Breeze;4",
"Rune: Thunder Shield;4",
"",
"Hydra IV Leech",
"0",
"Hydra IV [Leech];10",
"H4-Magma Frostblade;10",
"H4-Moor Ripper;10",
"H4-Moss Dragon;10",
"H4-Skeleton King;10",
"H4-Ice Dragon;10",
"H4-Fire Demon;10",
"H4-Behemoth;10",
"H4-Blackstone;10",
"H4-Stone Taurus;10",
"Rune: Avalanche;4",
"Rune: Transparency;4",
"Rune: Quicksand;4",
"Rune: Explosion;4",
"",
"Hydra IV Snipe",
"0",
"Hydra IV [Snipe];10",
"H4-Moss Dragon;10",
"H4-Moss Dragon;10",
"H4-Terra Cotta Warrior;10",
"H4-Arctic Cephalid;10",
"H4-Arctic Cephalid;10",
"H4-Winged Tiger;10",
"H4-Frostree-Folk;10",
"H4-Taiga General;10",
"H4-Cacti Guardian;10",
"Rune: arctic freeze;4",
"Rune: clear spring;4",
"Rune: permafrost;4",
"Rune: frost bite;4",
"",
"Hydra IV Teleport",
"0",
"Hydra IV [Teleport];10",
"H4-Demonic Imp;10",
"H4-Fire Demon;10",
"H4-Armored Sumatran;10",
"H4-Taiga Archon;10",
"H4-Dragon Knight;10",
"H4-Dire Snapping Turtle;10",
"H4-Red Banded Dragon;10",
"H4-Night Elf Ranger;10",
"H4-Thunder Dragon;10",
"Rune: Burning soul;4",
"Rune: Charred;4",
"Rune: Lore;4",
"Rune: Thunder Shield;4",
"",
"Hydra V Exile",
"0",
"Hydra V [Exile];10",
"H5-Taiga General;10",
"H5-Taiga General;10",
"H5-Taiga General;10",
"H5-Taiga General;10",
"H5-Lava Destroyer;10",
"H5-Azula;10",
"H5-Azula;10",
"H5-Azula;10",
"H5-Azula;10",
"Rune: Burning Soul;4",
"Rune: Clear Spring;4",
"Rune: Arctic Freeze;4",
"Rune: Lore;4",
"",
"Hydra V Guard",
"0",
"Hydra V [Guard];10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Fire Demon;10",
"H5-Fire Demon;10",
"H5-Dire Snapping Turtle;10",
"H5-Arbiter of War;10",
"H5-Prince of the Forest;10",
"Rune: Thunder Shield;4",
"Rune: Lightning;4",
"Rune: Nimble Soul;4",
"Rune: Lore;4",
"",
"Hydra V Leech",
"0",
"Hydra V [Leech];10",
"H5-Ice Dragon;10",
"H5-Ice Dragon;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Crystal Emperor;10",
"H5-Taiga General;10",
"H5-Taiga General;10",
"H5-Fire Kirin;10",
"Rune: Thunder Shield;4",
"Rune: Arctic Freeze;4",
"Rune: Clear Spring;4",
"Rune: Nimble Soul;4",
"",
"Hydra V Retaliate",
"0",
"Hydra V [Retaliate];10",
"H5-Behemoth;10",
"H5-Behemoth;10",
"H5-Behemoth;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Moss Dragon;10",
"H5-Giant Mud Larva;10",
"H5-Grand Lich;10",
"Rune: Thunder Shield;4",
"Rune: Death zone;4",
"Rune: Red Valley;4",
"Rune: Stonewall;4",
"",
"Hydra V Witch",
"0",
"Hydra V [Witch];10",
"H5-Behemoth;10",
"H5-Behemoth;10",
"H5-Behemoth;10",
"H5-Ice Dragon;10",
"H5-Ice Dragon;10",
"H5-Giant Mud Larva;10",
"H5-Taiga General;10",
"H5-Taiga General;10",
"H5-Grand Lich;10",
"Rune: red valley;4",
"Rune: arctic freeze;4",
"Rune: clear spring;4",
"Rune: flying stone;4",
"",
};
